site_name: Grout
docs_dir: docs
site_url: https://grout.romm.app/
site_author: RomM Team
site_description: A RomM client for your retro doo-dad.
repo_url: https://github.com/rommapp/grout
repo_name: rommapp/grout
edit_uri: edit/main/docs/

theme:
  name: material
  logo: resources/img/isotipo.png
  favicon: resources/img/isotipo.png
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.integrate
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  language: en
  palette:
    scheme: slate
    primary: custom
    accent: custom
  custom_dir: overrides

plugins:
  - search
  - gh-admonitions
  - glightbox:
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Quick Start:
      - getting-started/index.md
      - Allium: getting-started/install-allium.md
      - ArkOS / dArkOS: getting-started/install-arkos.md
      - Batocera: getting-started/install-batocera.md
      - ES-DE (EmuDeck / RetroDECK): getting-started/install-esde.md
      - Knulli: getting-started/install-knulli.md
      - MinUI: getting-started/install-minui.md
      - muOS: getting-started/install-muos.md
      - NextUI: getting-started/install-nextui.md
      - Koriki: getting-started/install-koriki.md
      - Onion: getting-started/install-onion.md
      - ROCKNIX: getting-started/install-rocknix.md
      - Spruce: getting-started/install-spruce.md
      - TrimUI: getting-started/install-trimui.md
  - Usage:
      - User Guide: usage/guide.md
      - Reference: usage/reference.md
      - Settings Reference: usage/settings.md
      - Save Sync: usage/save-sync.md
      - CFW Specific Info:
          - Allium: platforms/allium.md
          - ArkOS / dArkOS: platforms/arkos.md
          - Batocera: platforms/batocera.md
          - ES-DE (EmuDeck / RetroDECK): platforms/esde.md
          - Knulli: platforms/knulli.md
          - Koriki: platforms/koriki.md
          - MinUI: platforms/minui.md
          - muOS: platforms/muos.md
          - NextUI: platforms/nextui.md
          - Onion: platforms/onion.md
          - ROCKNIX: platforms/rocknix.md
          - Spruce: platforms/spruce.md
          - TrimUI: platforms/trimui.md
  - Contributing:
      - contributing/index.md
      - Development Guide: contributing/development.md
      - State Machine Reference: contributing/state-machine.md
      - Kudos: contributing/kudos.md
  - FAQ: usage/faq.md

copyright: "&copy; 2025 RomM Team"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rommapp/grout
      name: rommapp/grout
    - icon: fontawesome/brands/discord
      link: https://discord.gg/P5HtHnhUDH
      name: RomM Discord

extra_css:
  - resources/css/theme.css

watch:
  - docs
  - mkdocs.yml
  - overrides
