version: '3'

tasks:

  all:
    desc: Package for all platforms
    deps: [ next, muos, knulli, spruce, rocknix, arkos, trimui, allium, onion, koriki, minui, batocera, batocera-x86, batocera-amd64, esde ]
    cmds:
      - echo "Packaging complete (16 platforms)"
    silent: true

  next:
    cmds:
      - rm -rf dist/Grout.pak
      - mkdir -p dist/Grout.pak/lib
      - cp build64/grout scripts/NextUI/launch.sh README.md LICENSE pak.json dist/Grout.pak
      - cp -R build64/lib/* dist/Grout.pak/lib/
      - chmod a+x dist/Grout.pak/grout dist/Grout.pak/launch.sh
    silent: true

  muos:
    cmds:
      - rm -rf dist/muOS dist/Grout.muxapp
      - mkdir -p dist/muOS/Grout/lib
      - cp build64/grout scripts/muOS/mux_launch.sh README.md LICENSE dist/muOS/Grout
      - cp -R build64/lib/* dist/muOS/Grout/lib/
      - cp -R scripts/muOS/resources dist/muOS/Grout/
      - chmod a+x dist/muOS/Grout/grout dist/muOS/Grout/mux_launch.sh
      - cd dist/muOS && zip -qr ../Grout.muxapp Grout
    silent: true

  knulli:
    cmds:
      - rm -rf dist/Knulli
      - mkdir -p dist/Knulli/Grout/lib
      - cp build64/grout scripts/Knulli/Grout.sh scripts/Knulli/logo.png README.md LICENSE dist/Knulli/Grout
      - cp -R build64/lib/* dist/Knulli/Grout/lib/
      - chmod a+x dist/Knulli/Grout/grout dist/Knulli/Grout/Grout.sh
    silent: true

  spruce:
    cmds:
      - rm -rf dist/Spruce
      - mkdir -p dist/Spruce/Grout/grout/lib64
      - mkdir -p dist/Spruce/Grout/grout/lib32/{miyoo,a30}
      - cp scripts/Spruce/* README.md LICENSE dist/Spruce/Grout
      - cp build64/grout dist/Spruce/Grout/grout/grout64
      - cp build32/grout dist/Spruce/Grout/grout/grout32
      - cp -R build64/lib/* dist/Spruce/Grout/grout/lib64/
      - cp -R vendored/miyoo/* dist/Spruce/Grout/grout/lib32/miyoo/
#      - cp -R vendored/a30/* dist/Spruce/Grout/grout/lib32/a30/ # uncomment once we will be able to have a30 correct .so in the repo
      - cp vendored/miyoo/libSDL2_ttf-2.0.so dist/Spruce/Grout/grout/lib32/a30/
      - cp vendored/miyoo/libSDL2_ttf-2.0.so.0 dist/Spruce/Grout/grout/lib32/a30/
      - chmod a+x dist/Spruce/Grout/grout/grout32 dist/Spruce/Grout/grout/grout64 dist/Spruce/Grout/launch.sh
    silent: true

  allium:
    cmds:
      - rm -rf dist/Allium
      - mkdir -p dist/Allium/Grout.pak/grout/lib
      - cp -R scripts/Allium/* dist/Allium/Grout.pak
      - cp build32/grout README.md LICENSE dist/Allium/Grout.pak/grout
      - cp -R vendored/miyoo/* dist/Allium/Grout.pak/grout/lib/
    silent: true

  onion:
    cmds:
      - rm -rf dist/Onion
      - mkdir -p dist/Onion/Grout/grout/lib
      - cp -R scripts/Onion/* dist/Onion/Grout
      - cp build32/grout README.md LICENSE dist/Onion/Grout/grout
      - cp -R vendored/miyoo/* dist/Onion/Grout/grout/lib/
    silent: true

  koriki:
    cmds:
      - rm -rf dist/Koriki
      - mkdir -p dist/Koriki/App/Grout/grout/lib
      - mkdir -p dist/Koriki/.simplemenu/apps/Imgs
      - cp scripts/Koriki/launch.sh README.md LICENSE dist/Koriki/App/Grout
      - cp build32/grout dist/Koriki/App/Grout/grout/
      - cp -R vendored/miyoo/* dist/Koriki/App/Grout/grout/lib/
      - cp scripts/Koriki/Grout.sh dist/Koriki/.simplemenu/apps/Grout.sh
      - cp scripts/Koriki/grout.png dist/Koriki/.simplemenu/apps/Imgs/Grout.png
      - chmod a+x dist/Koriki/App/Grout/launch.sh dist/Koriki/.simplemenu/apps/Grout.sh
    silent: true

  arkos:
    cmds:
      - rm -rf dist/ArkOS
      - mkdir -p dist/ArkOS/Grout/lib
      - cp scripts/ArkOS/Grout.sh dist/ArkOS/
      - cp build64/grout scripts/ROCKNIX/logo.png README.md LICENSE dist/ArkOS/Grout/
      - cp -R build64/lib/* dist/ArkOS/Grout/lib/
      - chmod a+x dist/ArkOS/Grout/grout dist/ArkOS/Grout.sh
    silent: true

  rocknix:
    cmds:
      - rm -rf dist/ROCKNIX
      - mkdir -p dist/ROCKNIX/Grout/lib
      - cp scripts/ROCKNIX/Grout.sh dist/ROCKNIX/
      - cp build64/grout scripts/ROCKNIX/logo.png README.md LICENSE dist/ROCKNIX/Grout/
      - cp -R build64/lib/* dist/ROCKNIX/Grout/lib/
      - chmod a+x dist/ROCKNIX/Grout/grout dist/ROCKNIX/Grout.sh
    silent: true

  trimui:
    cmds:
      - rm -rf dist/Trimui
      - mkdir -p dist/Trimui/Grout/grout/lib
      - cp scripts/Trimui/* README.md LICENSE dist/Trimui/Grout
      - cp build64/grout dist/Trimui/Grout/grout
      - cp -R build64/lib/* dist/Trimui/Grout/grout/lib/
      - chmod a+x dist/Trimui/Grout/grout/grout dist/Trimui/Grout/launch.sh
    silent: true

  minui:
    cmds:
      - rm -rf dist/MinUI
      - mkdir -p dist/MinUI/Grout.pak/lib64
      - mkdir -p dist/MinUI/Grout.pak/lib32
      - cp build64/grout dist/MinUI/Grout.pak/grout64
      - cp build32/grout dist/MinUI/Grout.pak/grout32
      - cp scripts/MinUI/launch.sh README.md LICENSE dist/MinUI/Grout.pak
      - cp -R build64/lib/* dist/MinUI/Grout.pak/lib64/
      - cp -R vendored/miyoo/* dist/MinUI/Grout.pak/lib32/
      - chmod a+x dist/MinUI/Grout.pak/grout64 dist/MinUI/Grout.pak/grout32 dist/MinUI/Grout.pak/launch.sh
    silent: true

  batocera:
    cmds:
      - rm -rf dist/Batocera-arm64
      - mkdir -p dist/Batocera-arm64/Grout/lib
      - cp scripts/Batocera/Grout.sh dist/Batocera-arm64/
      - cp build64/grout README.md LICENSE dist/Batocera-arm64/Grout/
      - cp -R build64/lib/* dist/Batocera-arm64/Grout/lib/
      - chmod a+x dist/Batocera-arm64/Grout/grout dist/Batocera-arm64/Grout.sh
    silent: true

  batocera-x86:
    cmds:
      - rm -rf dist/Batocera-x86
      - mkdir -p dist/Batocera-x86/Grout/lib
      - cp scripts/Batocera/Grout.sh dist/Batocera-x86/
      - cp buildx86/grout README.md LICENSE dist/Batocera-x86/Grout/
      - cp -R buildx86/lib/* dist/Batocera-x86/Grout/lib/
      - chmod a+x dist/Batocera-x86/Grout/grout dist/Batocera-x86/Grout.sh
    silent: true

  batocera-amd64:
    cmds:
      - rm -rf dist/Batocera-amd64
      - mkdir -p dist/Batocera-amd64/Grout/lib
      - cp scripts/Batocera/Grout.sh dist/Batocera-amd64/
      - cp build/grout README.md LICENSE dist/Batocera-amd64/Grout/
      - cp -R build/lib/* dist/Batocera-amd64/Grout/lib/
      - chmod a+x dist/Batocera-amd64/Grout/grout dist/Batocera-amd64/Grout.sh
    silent: true

  esde:
    cmds:
      - rm -rf dist/ESDE
      - mkdir -p dist/ESDE/Grout/lib
      - cp scripts/ESDE/Grout.sh dist/ESDE/
      - cp build/grout scripts/ROCKNIX/logo.png scripts/ESDE/gamecontrollerdb.txt README.md LICENSE dist/ESDE/Grout/
      - cp -R build/lib/* dist/ESDE/Grout/lib/
      - chmod a+x dist/ESDE/Grout/grout dist/ESDE/Grout.sh
    silent: true
